### ISSUE TITLE
When try to get stats of player i got deafault information about player

### ISSUE THREAD

**Issue by DrownSelf** [erunion/sport-api-specifications#10]
So, when, for example i make GET request by this URL
(https://statsapi.web.nhl.com/api/v1/people/8475726?stats=statsSingleSeason&season=20202021)
i have same information from this URL (https://statsapi.web.nhl.com/api/v1/people/8475726)

**Comment by MarchandMD** [comment]
Check ur URL. This one works: https://statsapi.web.nhl.com/api/v1/people/8475726/stats?stats=statsSingleSeason&season=20202021

**Comment by bbrewington** [comment]
@erunion recommend closing this issue.  See MarchandMD's fix in previous comment
