### ISSUE TITLE
Can't get list of conferences or divisions

### ISSUE THREAD

**Issue by dimitry-ishenko** [erunion/sport-api-specifications#7]
Used [openapi-generator](https://github.com/OpenAPITools/openapi-generator) to create [NHL API Python client](https://github.com/dimitry-ishenko/nhl).

When I try to get a list of conferences, I get an dictionary with "copyright" and "teams" tags instead. The "teams" tag is obviously empty.

See repl.it example: https://repl.it/@dimitry_ishenko/nhl-api

Likewise, `DivisionsApi().get_divisions()` is not working.

On the other hand, `DraftApi().get_draft()`, `DraftApi().get_draft_prospects()`, `ScheduleApi().get_schedule()`, `StandingsApi().get_standing_type()`, `StandingsApi().get_standings()`, `StatsApi().get_stat_types()` and `TeamsApi().get_teams()` are working.

Quite a few other things also don't seem to work, eg: `TeamsApi().get_team(14)` does return a response, but all the field values are `None`.

I am new to all this, so I've no idear where things go wrong.

**Comment by erunion** [comment]
It's likely that the NHL has updated their API and the OpenAPI spec needs to be updated.
